name: lapor_book
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  intl: ^0.19.0
  url_launcher: ^6.2.2
  geolocator: ^10.1.0
  # firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  flutter_lints: ^3.0.1
  firebase_app_check: ^0.2.1+8

flutter:
  uses-material-design: true
  assets:  
  - assets/download.png